pipeline{
    agent any
    tools{
        nodejs "NodeJS"
        }

    stages{
        stage('Build'){
            steps{
                sh 'npm install'
            }
        }
        stage('Test'){
            steps{
                sh './jenkins/scripts/test.sh'
            }
        }
        stage('STAND AND DELIVER'){
            steps{
                sh.'/jenkins/scripts/deliver.sh'
                input message: 'finished using the web site? (click "Proceed" to continue)'
                sh './jenkins/scripts/kill.sh'
            }
        }
    }
}